default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dating_app_api_development

test:
  <<: *default
  database: dating_app_api_test

production:
  <<: *default
  database: dating_app_api_production
  username: username
  password: password
