default: &default
  adapter: adapter
  encoding: encoding
  pool: pool

development:
  <<: *default
  database: database

test:
  <<: *default
  database: database

production:
  <<: *default
  database: database
  username: username
  password: password